embedding_size: 64

# baby
weight_decay: 1e-3
n_ui_layers: 4
s_drop: 0.5
m_drop: 0.6
u_mm_image_weight: 0.2
i_mm_image_weight: 0
uu_co_weight: 0.4
ii_co_weight: 0.2
user_knn_k: 40
item_knn_k: 10
n_ii_layers: 1
n_uu_layers: 1
align_temp: 0.7
align_loss_weight: 5e-6
n_b: 4
multi_view_temp: 0.2
multi_view_loss_weight: 0.005

# # sports
# weight_decay: 5e-2
# n_ui_layers: 5
# s_drop: 1
# m_drop: 0.2
# u_mm_image_weight: 0
# i_mm_image_weight: 0.2
# uu_co_weight: 0.9
# ii_co_weight: 0.2
# user_knn_k: 25
# item_knn_k: 5
# n_ii_layers: 2
# n_uu_layers: 2
# align_temp: 1.5
# align_loss_weight: 1e-3
# n_b: 5
# multi_view_temp: 0.3
# multi_view_loss_weight: 0.001

# # clothing
# weight_decay: 1e-5
# n_ui_layers: 4
# s_drop: 0.4
# m_drop: 0.1
# u_mm_image_weight: 0
# i_mm_image_weight: 0.1
# uu_co_weight: 0.7
# ii_co_weight: 0.1
# user_knn_k: 45
# item_knn_k: 10
# n_ii_layers: 1
# n_uu_layers: 1
# align_temp: 0.03
# align_loss_weight: 1e-6
# n_b: 4
# multi_view_temp: 0.3
# multi_view_loss_weight: 0.001
