# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'clothing.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'
user_graph_dict_file: 'user_graph_dict.npy'
dict_user_co_occ_graph_file: "dict_user_co_occ_graph"
dict_item_co_occ_graph_file: "dict_item_co_occ_graph"

field_separator: "\t"
